version: '3.3'
services:
  instance-demo:
    env_file:
      - ./round-robin/instance/.env
      - ./.env # Global env
    command: uvicorn app.main:app --host 0.0.0.0
    build:
      context: ./round-robin
      dockerfile: ./instance/Dockerfile
      args:
        INSTALL_ENV: production
    deploy:
      replicas: ${NO_INSTANCES}
    ports:
      - '8001-8005:8000'
    volumes:
      - ./round-robin/instance:/app/
  round-robin:
    env_file:
      - ./round-robin/robin/.env
      - ./.env # Global env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    build:
      context: ./round-robin
      dockerfile: ./robin/Dockerfile
      args:
        INSTALL_ENV: production
    ports:
      - '8000:8000'
    volumes:
      - ./round-robin/robin:/app/
volumes:
  cache:
    driver: local
